seed: 42
device: "cuda"
log_to_wandb: true
project_name: "GMAE-Finetune"
run_name: "gmae-base-finetune"
save_dir: "/home/student/projects/gmae/checkpoints/finetune"

data_path: "/home/student/projects/gmae/data/pretrain_dataset"
pretrained_checkpoint: "/home/student/projects/gmae/checkpoints/pretrain/checkpoint_49.pth"
in_channels: 3
img_size: 224
batch_size: 16
num_workers: 8
num_classes: 18

patch_size: 16
embed_dim: 768
depth: 12
num_heads: 12
mlp_ratio: 4.0
dilation_rates: [1, 3, 5]
ffn_kernel_sizes: [3, 5, 7]

epochs: 250
lr: 1e-4
weight_decay: 0.01
warmup_epochs: 10
freeze_encoder_epochs: 5
save_freq: 20
fp16: true