seed: 42
device: "cuda"
log_to_wandb: false
run_name: "gmae-inference"

data_path: "/home/student/projects/gmae/data/test_dataset"
checkpoint_path: "/home/student/projects/gmae/checkpoints/finetune/best_model.pth"
output_dir: "/home/student/projects/gmae/results/inference"

in_channels: 3
img_size: 224
batch_size: 32
num_workers: 4

patch_size: 16
embed_dim: 768
depth: 12
num_heads: 12
decoder_embed_dim: 512
decoder_depth: 8
decoder_num_heads: 16
mlp_ratio: 4.0
dilation_rates: [1, 3, 5]
ffn_kernel_sizes: [3, 5, 7]

mask_ratio: 0.0
num_samples_to_visualize: 10  
save_reconstructions: true
fp16: true